Upgrade pyyaml
Due to error when making wheel:

********************************************************************************
The license_file parameter is deprecated, use license_files instead.

By 2023-Oct-30, you need to update your project and remove deprecated calls
or your builds will no longer be supported.

See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
********************************************************************************

.. and:

  ..
  File "/tmp/pip-build-env-t5qvm1g_/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
    raise AttributeError(attr)
AttributeError: cython_sources